# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FPT Play Box - Hộp giải trí gia đình
email: contact@myphamnaotot.com
description: > # this means to ignore newlines until "baseurl:"
  Mua hộp truyền hình FPT PLay(android tv box) để xem tivi online
  truyền hình trực tuyến gồm thời sự, tin tức, thể thao, bóng đá...và những bộ phim Âu, Á, Mỹ, Hàn hay nhất.
  Ngoài ra với chất lượng âm thanh dolby 5.0 cho bạn cảm giác trải nghiệm tuyệt vời hơn khi nghe nhacso trên hộp truyền hình FPT PLay.
  Click ngay để đặt hàng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fptplaybox.net" # the base hostname & protocol for your site

price: 2.190.000
phone: 08 6274 7274
email: sales@fptplaybox.net

# Build settings
markdown: kramdown
navigation:
- text: Trang Chủ
  url: /
- text: So sánh với IPTV Box 700K
  url: /compare.html
- text: Cài Đặt
  url: /box.html
- text: Hỗ Trợ
  url: /support.html
- text: Danh sách kênh
  url: /channels.html
- text: Mua Ngay
  url: /order.html